server:
  port: 8762

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  routes:
    book-service:
      path: /library/**
      service-id: library-service
    auth-service:
      path: /auth/**
      service-id: auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
    storage-service:
      path: /storage/**
      serviceId: storage-service
  host:
      connect-timeout-millis: 60000
      socket-timeout-millis: 60000
